runtime: nodejs20
env: standard
service: tus-protocol

env_variables:
  GCS_BUCKET_NAME: "tus-upload-test"
  GCS_AGENT_INVENTORY_BUCKET_NAME: "iqol-crm"
  GCS_PROJECT_ID: "iqol-crm"

automatic_scaling:
  min_instances: 0

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10