runtime: custom
env: flex
service: tus-protocol

env_variables:
  GCS_BUCKET_NAME: "tus-upload-test"
  GCS_PROJECT_ID: "iqol-crm"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10